# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: 2..3
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
params:
  themeColor: "theme-base-0d"
  h_min: 2
  h_max: 3

# Setup
title: NOVA Search
tagline: Web and Media Search Lab
url: http://wiki.novasearch.org
baseurl: /

author:
  name: NOVA Search Contributors
  url: http://wiki.novasearch.org

# Custom variables for Hyde theme
version: "1.0"
github:
  repo: https://github.com/novasearch/wiki.novasearch.org
