# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Setup
title: NOVA Search
tagline: Web and Media Search Lab
url: http://novasearch.github.io
baseurl: /

author:
  name: NOVA Search Contributors
  url: http://novasearch.github.io

# Custom variables for Hyde theme
version: "1.0"
github:
  repo: https://github.com/novasearch/novasearch.github.io
params:
  themeColor: "theme-base-09"
